version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: expediciones_db
    environment:
      POSTGRES_DB: expediciones_db
      POSTGRES_USER: expediciones
      POSTGRES_PASSWORD: expediciones123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
